### ISSUE TITLE
feature parity checklist

### ISSUE THREAD

**Issue by hoodie** [ascii-dresden/asciii#49]
- [x] `list`
  - [x] `--wages`
  - [x] `--no-colors`
  - [x] `--filter`
  - [x] `--caterers`
  - [ ] <s>`--blockers`</s>
  - [x] `--edit <index>` (
  - [x] `--archive [<year>]` (with default value)
- [x] `edit`
  - [x] <s>`--config`</s>
  - [ ] <s>select by index</s>
- [x] `show`
  - [x] `--errors`
- [x] `output` ( = `path --output`
- [x] `calendar` 📆
